FROM python:3.10-slim

WORKDIR /opt/program

COPY algorithms/training/requirements.txt /opt/program/requirements.txt
RUN pip install --no-cache-dir -r /opt/program/requirements.txt

COPY . /opt/program

RUN cp /opt/program/algorithms/training/train /usr/local/bin/train && \
    cp /opt/program/algorithms/training/serve /usr/local/bin/serve && \
    chmod +x /usr/local/bin/train && \
    chmod +x /usr/local/bin/serve

ENV PYTHONPATH="/opt/program"
ENV PYTHONUNBUFFERED=1

EXPOSE 8080